import { CoursesProvider } from '@/context/coursesContext'; // OK
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // OK: app ディレクトリ内の相対パス

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "履修単位計算アプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <CoursesProvider> {/* ここでラップ */}
          {children}
        </CoursesProvider>
      </body>
    </html>
  );
}